# The GitHub labels to be used by this repo
- name: bug
  description: If this is a bug
  color: 800000
- name: security/privacy
  description: If it involves securing user information
  color: 000000
- name: design
  description: If it needs a large amount of design
  color: f032e6
- name: optimization
  description: If it's related to performance
  color: ffe119
- name: copy
  description: If it's only a copy change, or needs a large amount of copy
  color: 469990
- name: onboarding
  description: If it has to do with educating users on using the product
  color: aaffc3
- name: feature request
  description: If it's a feature request from a user
  color: e6beff
