name: 'Notion x GitHub Action'
description: 'Sync GitHub issues to a Notion database'
inputs:
  notion-token:
    description: 'Your Notion API Token'
    required: true
  notion-task-db:
    description: 'The Notion task database id'
    required: true
  notion-project-db:
    description: 'The Notion project database id'
    required: true
  notion-users-db:
    description: 'The Notion users database id'
    required: true
  github-token:
    description: 'Your GitHub personal access token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
