name: 'Notion x GitHub Action'
description: 'Sync GitHub issues to a Notion'
inputs:
  notion-token:
    description: 'Your Notion API Token'
    required: true
  notion-task-ds:
    description: 'The Notion task data source id'
    required: true
  notion-project-ds:
    description: 'The Notion project data source id'
    required: true
  notion-users-ds:
    description: 'The Notion users data source id'
    required: true
  github-token:
    description: 'Your GitHub personal access token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
