name: 'Notion x GitHub Action'
description: ''
inputs:
  notion-token:
    description: 'Your Notion API Token'
    required: true
  notion-db:
    description: 'The Notion database id'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
