name: Sync GitHub Issues to Notion

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, assigned, unassigned, closed, reopened]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Generate GitHub App Token
      id: get_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.NOTION_SYNC_APP_ID }}
        private-key: ${{ secrets.NOTION_SYNC_APP_KEY }}

    - name: Notion Sync Action
      uses: Gisat/ptr-github-issues-for-notion@wip
      with:
        notion-token: ${{ secrets.NOTION_TOKEN }}
        notion-db: ${{ secrets.NOTION_DATABASE }}
        github-token: ${{ steps.get_token.outputs.token }}