name: "Milestones on autopilot"
on:
  schedule:
  - cron: "*/20 * * * *"

jobs:
  milestones:
    runs-on: ubuntu-latest
    steps:
    - uses: instantish/memorable-milestones@2.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
